# Generated by Django 4.0.3 on 2022-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0002_alter_room_people_count'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('room', 'date'), name='unique_room_reservation'),
        ),
    ]
