# Generated by Django 4.0.3 on 2022-05-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0003_reservation_unique_room_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date']},
        ),
    ]
