# Generated by Django 4.0.3 on 2022-05-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0004_alter_reservation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_people_count',
            field=models.PositiveSmallIntegerField(default=30),
            preserve_default=False,
        ),
    ]
