# Generated by Django 4.0.3 on 2022-05-22 09:40
# with: python manage.py makemigrations --empty --name fill_in_user_link buildingmanagement

from django.db import migrations
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0006_reservation_user_link'),
    ]

    def fill_in_user_link(self, apps, schema_editor):
        Reservation = apps.get_model('buildingmanagement', 'Reservation')
        User = settings.AUTH_USER_MODEL
        for r in Reservation.object.all():
            r.user_link = User.object.get(name=r.user)

    operations = [
        migrations.RunPython(fill_in_user_link)
    ]
