# Generated by Django 4.0.3 on 2022-05-22 09:40
# with: python manage.py makemigrations --empty --name fill_in_user_link buildingmanagement

from django.db import migrations
from django.conf import settings

def fill_in_user_link(apps, schema_editor):
    Reservation = apps.get_model('buildingmanagement', 'Reservation')
    User = apps.get_model('auth', 'User')
    for r in Reservation.objects.all():
        r.user_link = User.objects.get(username=r.user)
        r.save()

def clear_user_link(apps, schema_editor):
    Reservation = apps.get_model('buildingmanagement', 'Reservation')
    for r in Reservation.objects.all():
        r.user_link = None
        r.save()

class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0006_reservation_user_link'),
    ]

    operations = [
        migrations.RunPython(fill_in_user_link, clear_user_link)
    ]
