# Generated by Django 4.0.3 on 2022-05-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0009_remove_reservation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user_link',
            new_name='user',
        ),
    ]
