# Generated by Django 4.0.3 on 2022-05-22 11:01

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0010_rename_user_link_reservation_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('people_count__lte', django.db.models.expressions.F('max_people_count'))), name='people_count_maximum'),
        ),
    ]
