# Generated by Django 4.0.3 on 2022-05-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0011_room_people_count_maximum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buildingmanagement.room')),
            ],
        ),
    ]
