# Generated by Django 4.0.3 on 2022-05-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0013_accesscard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscard',
            name='rooms',
            field=models.ManyToManyField(related_name='accesscards', to='buildingmanagement.room'),
        ),
    ]
