# Generated by Django 4.0.3 on 2022-06-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0014_alter_accesscard_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
