# Generated by Django 4.0.4 on 2022-04-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='biketype',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservations.biketype'),
            preserve_default=False,
        ),
    ]
